create database Alunos
use  Alunos
create table TB_CLASSE (
ID_classe smallint,
ID_Andar smallint
);
create table TB_ESTADO (
SIGLA_ESTADO char(2) NOT NULL,
NOME_ESTADO varchar(40)

);
create table TB_DICIPLINA (
ID_DICIPLINA char(3),
NOME_DICIPLINA varchar(15),
ID_PROFESSOR_DICIPLINA char(3),
NOTA_MINIMA_DICIPLINA smallint
);
create table TB_ALUNO(
COD_ALUNO smallint,
Nome_Aluno varchar(45),
END_ALUNO varchar(100),
SIGLA_ESTADO char(2),
ID_CLASSE SMALLINT
);
create table TB_PROFESSOR (
ID_PROFESSOR char(3),
ID_ANDAR SMALLINT

);
create table TB_ALUNO_DICIPLINA(
COD_ALUNO smallint,
ID_DICIPLINA char (3),
NOTA_ALUNO smallint
);
/*CRIAÇÃO DE PRIMARY KEY*/
/*ESTADO*/
ALTER TABLE TB_ESTADO ADD CONSTRAINT PK_SIGLA_ESTADO PRIMARY KEY 
(SIGLA_ESTADO);
/*CLASSE*/
ALTER TABLE TB_CLASSE ADD CONSTRAINT PK_ID_CLASSE primary key (ID_CLASSE);
/*ALUNO*/
ALTER TABLE TB_ALUNO ADD CONSTRAINT PK_COD_ALUNO PRIMARY KEY (COD_ALUNO);
/*PROFESSOR */
ALTER TABLE TB_PROFESSOR ADD CONSTRAINT PK_ID_PROFESSOR primary key (ID_PROFESSOR);
/*DICIPLINA*/
ALTER TABLE TB_DICIPLINA ADD CONSTRAINT PK_ID_DICIPLINA primary key (ID_DICIPLINA);

/*FOREIGN KEYS*/
/*ESTADO-ALUNO*/
ALTER TABLE TB_ALUNO
ADD CONSTRAINT FK_TB_ALUNO_TB_ESTADO FOREIGN KEY (SIGLA_ESTADO) REFERENCES TB_ESTADO (SIGLA_ESTADO);
/*CLASSE-ALUNO*/
ALTER TABLE TB_ALUNO 
ADD CONSTRAINT FK_TB_ALUNO_TB_CLASSE FOREIGN KEY (ID_CLASSE) REFERENCES TB_CLASSE (ID_CLASSE);
/*ALUNO-DICIPLINA-DICIPLINA
*/
ALTER TABLE TB_ALUNO_DICIPLINA 
ADD CONSTRAINT FK_TB_ALUNO_DICIPLINA_TB_ALUNO FOREIGN KEY  (COD_ALUNO) REFERENCES TB_ALUNO (COD_ALUNO);
/*
DICIPLINA-ALUNO
*/
ALTER TABLE TB_ALUNO_DICIPLINA 
ADD CONSTRAINT FK_TB_DICIPLINA_TB_DICIPLINA FOREIGN KEY (ID_DICIPLINA) REFERENCES TB_DICIPLINA (ID_DICIPLINA);

/*
DICIPLINA-PROFESSOR
*/
ALTER TABLE TB_DICIPLINA ADD CONSTRAINT FK_ID_DICIPLINA_TB_PROFESSOR FOREIGN KEY (ID_PROFESSOR_DICIPLINA) REFERENCES TB_PROFESSOR (ID_PROFESSOR);



 

    